env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "DoraCore"
    TG_TOKEN: "ENCRYPTED[b6d40dfd0ee5e1970c26239ace15a3131f7f232494471474b725179690b20ecd6bbff0bd6fcaaaa41feee7d42c2040db]"
    CIRRUS_WORKING_DIR: "/home/doraemon"

task:
  name: DoraCore Kernel CirrusCI
  container:
    image: dopaemon/focal:latest
    cpu: 16
    memory: 4G
    kvm: true

  setup_script:
    - sudo apt-get update -y && sudo apt-get install -y curl wget liblz4-1 libyaml-0-2 p7zip-full gcc g++ bison bc make git zip flex zipalign libssl-dev python3 gcc-aarch64-linux-gnu cpio tree vim bc bison build-essential ccache curl flex git gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

  clone_script:
    - cd $CIRRUS_WORKING_DIR
    - mkdir ~/bin
    - export PATH=~/bin:$PATH
    - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod a+x ~/bin/repo
    - mkdir android-kernel && cd android-kernel
    - repo init --depth=1 -u https://github.com/dopaemon/android_kernel_xiaomi_common.git -b manifest
    - repo sync --force-sync --no-clone-bundle --no-tags | tee sync.txt
    - rm -rf .git .github .repo
    - rm -rf common
    - git clone -b main --single-branch --depth=1 https://gitlab.com/mcdofrenchfreis/android-clang-14.0.7.git prebuilts-master/clang/host/linux-x86/clang-r547379
    - cd ./build
    - rm -rf _setup_env.sh
    - wget https://raw.githubusercontent.com/dopaemon/android_kernel_xiaomi_common/refs/heads/master/.github/scripts/_setup_env.sh
    - chmod +x _setup_env.sh
    - cd ../
    - git clone -b Rebase --single-branch --depth=1 https://github.com/dopaemon/android_kernel_xiaomi_common.git common
    - git clone -b lineage-22.1 --single-branch --depth=1 https://github.com/cupid-development/android_kernel_xiaomi_sm8450-modules.git sm8450-modules

  build_script:
    - cd $CIRRUS_WORKING_DIR/android-kernel
    - LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh -j$(nproc --all) | tee log.txt

  compress_script:
    - export VERSION="DoraCore-GKI-5.10-A12-$(date '+%Y-%m%d-%H%M')"
    - cd $CIRRUS_WORKING_DIR
    - git clone -b master --depth=1 https://github.com/dopaemon/Anykernel3.git ./AnyKernel3
    - cp -r android-kernel/out/android12-5.10/dist/Image.gz AnyKernel3/
    - cd AnyKernel3
    - zip -rv9 $VERSION.zip *
    - mv $VERSION.zip $CIRRUS_WORKING_DIR/

  telegram_script:
    - export VERSION="DoraCore-GKI-5.10-A12-$(date '+%Y-%m%d-%H%M')"
    - cd $CIRRUS_WORKING_DIR
    - echo $(curl -F document=@"$VERSION.zip" https://api.telegram.org/bot$TG_TOKEN/sendDocument?chat_id=1186034226)
